### PR TITLE
Divider separators

### PR DESCRIPTION
**Pull request by cibersheep**
Tweak the Divider spacer:

before:

imatge

After:

imatge

Before:
imatge

After:
imatge

### CODE REVIEW

**Comment by cibersheep** [comment]
Would close #66 but what do you think?
I tried a 1 gu Rectangle but looks really out of place

**Review by mariogrip — APPROVED** [review]
LGTM :+1: 

This should also give a minor performance boost. 

Can you rebase on top of xenial?

**Comment by cibersheep** [comment]
Let's see if I rebased correctly

**Comment by cibersheep** [comment]
Apparently it build against armhf but not the other architectures.
`bailout 1 'Error: Failed to build with cowbuilder.'`
Is there something I must do here?

**Comment by dobey** [comment]
> Apparently it build against armhf but not the other architectures.
> `bailout 1 'Error: Failed to build with cowbuilder.'`
> Is there something I must do here?

It failed the API check, since the API was changed:
```
Verifying the diff between existing and generated API
--- /build/ubuntu-ui-toolkit-1.3.2192~0ubports2+0~20210215015431.7~1.gbp9a97c4/components.api	2021-02-15 01:54:30.000000000 +0000
+++ /build/ubuntu-ui-toolkit-1.3.2192~0ubports2+0~20210215015431.7~1.gbp9a97c4/components.api.new	2021-02-15 02:29:01.061437004 +0000
@@ -427,7 +427,11 @@ Ubuntu.Components.Popups.Dialog 1.3: Pop
     property ThemeSettings theme
     property string title
 Ubuntu.Components.ListItems.Divider 1.0 0.1: QQuickImageBase
-Ubuntu.Components.ListItems.Divider 1.3: QQuickImageBase
+Ubuntu.Components.ListItems.Divider 1.3: Item
+    readonly property QQuickPen border
+    property color color
+    property QJSValue gradient
+    property double radius
 Ubuntu.Components.DragDirection: Enum
     Downwards
     Undefined

Differences in API. Did you forget to update components.api?
Makefile:469: recipe for target 'check' failed
```

**Comment by cibersheep** [comment]
After changing components.api I still get:

```
 Ubuntu.Components.ListItems.Divider 1.0 0.1: QQuickImageBase
 Ubuntu.Components.ListItems.Divider 1.3: Item
+    readonly property QQuickPen border
+    property color color
+    property QJSValue gradient
+    property double radius
```

Why is it?

**Comment by dobey** [comment]
> Why is it?

Yes, you didn't add those as you should have. You changed the base of the widget from `Image` to `Rectangle` so now it has those properties. They probably shouldn't be exposed, I guess, so instead you should make the toplevel item inside `Divider.qml` be an `Item` and then make the `Rectangle` as a child of it.

**Comment by cibersheep** [comment]
Ah. I see. Thanks.
I'll do the changes later

**Comment by cibersheep** [comment]
Mhm. I made the suggested changes but still failing in the components.api check:
https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubuntu-ui-toolkit/detail/PR-80/10/pipeline/#step-37-log-2281

I don't know how to proceed

**Comment by dobey** [comment]
> After changing components.api I still get:
> 
> ```
>  Ubuntu.Components.ListItems.Divider 1.0 0.1: QQuickImageBase
>  Ubuntu.Components.ListItems.Divider 1.3: Item
> +    readonly property QQuickPen border
> +    property color color
> +    property QJSValue gradient
> +    property double radius
> ```
> 
> Why is it?

Perhaps it would be better to switch it to having the root item be a `Rectangle` and just list these properties as described, in the `components.api` file, since it's much fewer items.

Could you also please rebase and squash your commits after fixing that? Thanks.

**Comment by cibersheep** [comment]
Roger!
I'll do that today or tomorrow if that's ok

**Comment by dobey** [comment]
Sure. We're trying to get PRs merged or closed, so @peat-psuwit can get uitk migrated to GitLab under the `lomiri-ui-toolkit` repo. :)

**Comment by cibersheep** [comment]
I hope I did that correctly (the squashing)

**Review by dobey — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
