### PR TITLE
Add default width/height hints for MainView

### PR DESCRIPTION
**Pull request by dpniel**
These are the same defaults as are provided by the ubuntu-sdk-ide
templates

Fixes: https://github.com/ubports/ubuntu-touch/issues/364

### CODE REVIEW

**Comment by dpniel** [comment]
I didn't modify MainWindow as it's still just a labs component and the docs clearly state setting `minimumWidth` and `minimumHeight`

**Review by sverzegnassi — APPROVED** [review]
LGTM

**Comment by sverzegnassi** [comment]
Question, was this meant to go into OTA-3? I see we have no CI set up for UITK yet

**Comment by dpniel** [comment]
I'm really not sure if we should get this in for OTA-3, it's not critical or anything. I just sent the PR as it was a quick fix :-)

Would be good to get the UITK setup on CI though

**Pull request merged**
