### PR TITLE
Add support for newer qt version

### PR DESCRIPTION
**Pull request by mariogrip**
This pulls in fixes from @z3ntu where I made those compile on lesser version using `#ifdef` 

Thanks @z3ntu for the fixes :)

### CODE REVIEW

**Comment by mariogrip** [comment]
@z3ntu if you have time, could you make sure this builds on newer versions too?

**Comment by z3ntu** [comment]
I can only test with Qt 5.14 at the time and additional fixes in #62 it compiles fine. Launching `./gallery.sh` and clicking through the window seems to work fine (except the images not being found but that's probably because I don't have the Suru icons installed)

**Comment by z3ntu** [comment]
I wonder if we can somehow get CI for multiple Qt versions but I'm not aware of a distro packaging multiple Qt versions. 
I wonder if we can use flatpak for that though, flathub has runtimes with Qt 5.9, 5.11, 5.12 and 5.13

**Comment by mariogrip** [comment]
> I wonder if we can somehow get CI for multiple Qt versions but I'm not aware of a distro packaging multiple Qt versions.
> I wonder if we can use flatpak for that though, flathub has runtimes with Qt 5.9, 5.11, 5.12 and 5.13

This is a good idea, but since we are moving to gitlab (soon ish) it might be easier to use docker (https://hub.docker.com/r/darkmattercoder/qt-build) for this

**Comment by z3ntu** [comment]
Haven't thought about Docker, seems like a good use case for this!

Anyways, #62 should be merged (that PR targets the branch of this PR), then I'm happy :)

**Comment by mariogrip** [comment]
Added some pretty ci here: https://gitlab.com/ubports/core/ubuntu-ui-toolkit/merge_requests/1

**Comment by z3ntu** [comment]
Also if we move these changes into xenial, can we remove the bionic branch? And maybe rename xenial to master?
From my side a perfect ubports repo branch setup would be:
* master: Builds with the latest and greatest (=Arch, Alpine) but also supports the latest ubports version (so currently xenial)
* If there are completely incompatible changes or changes that are only needed for xenial rootfs, make a xenial branch that's based on master (but changes should also land in master, not just in xenial..)

**Review by UniversalSuperBox — APPROVED** [review]
@z3ntu, I agree that would be better. However I think we'll have to settle with landing things semi-manually for now. Our current CI setup won't build one commit multiple times for multiple releases (and ignore if there's a branch for that release, for example). I don't doubt we could make it do that, given time we don't currently have.

@mariogrip, I'm approving this on static analysis and checking on 5.9 on our devices. It's up to you to determine if the other versions are right before merging.

**Pull request merged**
