### PR TITLE
Use a Ash Grey for Default Button Color

### LINKED ISSUE #41: Default Grey Color for Buttons
If not set, a Button color [will be #b2b2b2 grey by default](https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml#L29) but that's a grey that is not in the system palette

I suggest using Ash #888888 grey for default grey button color as it works well with Ambient and SuruDark

imatge

### PR DESCRIPTION
**Pull request by cibersheep**
Default grey used before was not in the palette.
Fixes #41

### CODE REVIEW

**Comment by mardy** [comment]
I would rather add the existing color to the palette; I feel that a lighter grey looks much better.

**Comment by cibersheep** [comment]
I understand but #b2b2b2 is not used in any other place than in the default button color. It feels more like a mistake or a left over

**Comment by dobey** [comment]
> I understand but #b2b2b2 is not used in any other place than in the default button color. It feels more like a mistake or a left over

It's also used in version 1.2 fo the Ambiance style, in two places:
```
ubuntu-ui-toolkit/src/imports/Components/Themes/Ambiance/1.2/ComboButtonStyle.qml:        defaultColor: "#b2b2b2"
ubuntu-ui-toolkit/src/imports/Components/Themes/Ambiance/1.2/ButtonStyle.qml:    property color defaultColor: "#b2b2b2"
```

**Comment by cibersheep** [comment]
> `ubuntu-ui-toolkit/src/imports/Components/Themes/Ambiance/1.2/ComboButtonStyle.qml: defaultColor: "#b2b2b2"`

Which was updated on 1.3 to `foreground`. #b2b2b2 is a left over from old style
https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/ComboButtonStyle.qml#L48

**Comment by dobey** [comment]
@cibersheep Sure, but if we're changing the color (btw, it says in the comment you removed it should be added to the palette), why shouldn't we also adjust it in the `1.2` style, for the case where apps are still using the older imports?

**Comment by cibersheep** [comment]
> @cibersheep Sure, but if we're changing the color (btw, it says in the comment you removed it should be added to the palette), why shouldn't we also adjust it in the `1.2` style, for the case where apps are still using the older imports?

Interesting. I would say that we leave 1.2 as it is as is superseded by 1.3 (which if I remember correctly, has other color tweaks as the blue for focus instead of green).

**Review by dobey — APPROVED** [review]

**Pull request merged**
