### PR TITLE
Adapt to QtPim API changes

### LINKED ISSUE #9: defaultCollection() was replaced by defaultCollectionId()
Branch: `bionic`

Fails to building using the latest [qtpim](http://code.qt.io/cgit/qt/qtpim.git/commit/) built from source

```
error: ‘class QtOrganizer::QOrganizerManager’ has no member named ‘defaultCollection’; did you mean ‘defaultCollectionId’?
```

[This commit](http://code.qt.io/cgit/qt/qtpim.git/commit/?id=18e3d741c3526978cdacc88bc260d250918d2080) replaced `defaultCollection()` with `defaultCollectionId()`

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #9

~~Feel free to split up the commits, take half of it or whatever
Commit message should really be changed before merging at least.~~

### CODE REVIEW

**Review by mardy — APPROVED** [review]
Looks good!

**Comment by z3ntu** [comment]
I've split up the commits now. Content is the same.

**Review by mardy — APPROVED** [review]

**Comment by vanyasem** [comment]
You probably also need this https://github.com/ubports/ubuntu-ui-toolkit/commit/4f2691b336dedbbeee66434cfafce211170e659a#diff-d837a1c17de0268bcea321239ddbed47

**Review by dobey — CHANGES_REQUESTED** [review]
Are there open issues which these changes are supposed to fix? I think these should probably also be split up into separate PRs as they seem unrelated to each other. And tests probably need updating too.

**Comment by mardy** [comment]
@dobey, please notice that these are three different commits; if they are merged with the "Rebase and merge" option, they'll land as separate commits. I can't talk about the other two commits, but the one about QtPim is a needed fix which we already have in the `xenial` branch (without it, the package fails to build against a recent QtPim).

**Comment by dobey** [comment]
@mardy I wasn't suggesting they weren't separate commits. I was suggesting they should be separate branches with separate PRs, because they fix separate things, and that what they're fixing needs to be documented in some way (preferably with an issue being fixed), and they need tests.

**Comment by z3ntu** [comment]
"Add option to disable building of docs" just adds an option for qmake not to build the docs.

"Fix "Missing sentinel in function call" warning" fixes a compilation warning that I got when building ubuntu-ui-toolkit on Alpine.

And the first commit was explained by @mardy.

I can split the PR into 3 PRs if that's really wanted :)

**Comment by dobey** [comment]
Well it seems that the "compiles with newer qtpim" doesn't actually fix it, as you can see at the failed CI check log.

**Comment by z3ntu** [comment]
Probably because the CI has an older version of qtpim installed that doesn't need that change.

**Comment by vanyasem** [comment]
It fails to compile because of that: https://github.com/ubports/ubuntu-ui-toolkit/pull/20#issuecomment-427595220. You need to specify that there's no need to install older qtpim in debian/control

**Comment by z3ntu** [comment]
@vanyasem I added that but it still fails to build.
```
The following packages have unmet dependencies:

 pbuilder-satisfydepends-dummy : Depends: qtpim5-dev (>= 5.0~git20171109~0bd985b) but it is not going to be installed
```

**Comment by dobey** [comment]
It fails, because the newer qtpim is not packaged in bionic. I think we should close this PR and open issues for any problems there are, and we'd need to do a concerted effort to get latest qtpim into bionic builds, along with the necessary changes for qtpim into bionic branches. And we need proper testing for things like this. For example, I don't know what warning is fixed by adding a char* cast to a NULL, but it feels wrong looking at that change.

**Comment by z3ntu** [comment]
The exact warning without the patch is
```
ucurihandler.cpp: In constructor 'UCUriHandler::UCUriHandler()':
ucurihandler.cpp:78:73: error: missing sentinel in function call [-Werror=format=]
     char* path = nih_dbus_path(NULL, "", applicationId.constData(), NULL);
                                                                         ^
```
(error because of -Werror)

**Comment by dobey** [comment]
OK, `(char *)NULL` is the wrong fix for that. Those NULLs probably need to be `nullptr` instead. I suspect there are probably more such cases if this one is in here. Please open an issue about that.

**Comment by z3ntu** [comment]
Opened #23 and #24 and removed those commits from this PR.

**Comment by z3ntu** [comment]
@dobey (about the "missing sentinel" warning) Quote from https://stackoverflow.com/a/12122764/3527128:
> The problem with the first version is that the list of parameters is meant to end with a null pointer. But '\0' is not a null pointer, it's a null character. So the value (0) is correct, it's just the type is wrong.
> The (char *)0 is also zero, but cast as a char pointer, which is a null pointer (ie it points to address 0)

**Review by dobey — APPROVED** [review]

**Review by dobey — CHANGES_REQUESTED** [review]
I'm setting my review back to request changes, as it seems the new qtpim version is not available in the UBports bionic repos. It will need to be there, with a successful build in CI, before we can merge this.

**Comment by z3ntu** [comment]
I think there should be a "master" branch (for every repo) containing changes needed for the most recent versions of everything (Qt stack, etc) and then the Ubuntu-specific xenial & bionic branches can merge that stuff in if needed. 
I think that would be the best way to simplify support for other distros that are not Ubuntu (Touch).

**Comment by dobey** [comment]
> I think there should be a "master" branch (for every repo) containing changes needed for the most recent versions of everything (Qt stack, etc) and then the Ubuntu-specific xenial & bionic branches can merge that stuff in if needed.
> I think that would be the best way to simplify support for other distros that are not Ubuntu (Touch).

I don't disagree, but that's unrelated to whether the branch would have the dependencies satisfied in CI building. Ubuntu 18.04 is a supported target for x86 builds of the Unity8 stack, and so we shouldn't merge changes which we know will break that platform. The primary development target is Ubuntu, and so for changes to merge, the changes must not break the installs on Ubuntu, regardless of whether they fix things on other distros.

**Comment by dobey** [comment]
I've packaged the updated qtpim for bionic. I've also opened PR #30 which merges up some changes from xenial and gets the builds passing again. As part of that, it includes the same changes as this branch, so I'm going to close this PR, since this same change is included their via the xenial changes. Thanks.

**Pull request closed without merging**
